[project]
name = "wetransfer-downloader"
version = "0.1.0"
description = "Secure WeTransfer downloader with CLI and FastAPI microservice."
authors = [
    { name = "Nikos Sokos" }
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn",
    "playwright",
    "requests",
]

[project.scripts]
wtdownload = "wetransfer_downloader.cli:main"

[tool.uv]
package = true  # required for CLI entrypoints

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
